### ISSUE TITLE
We're still not be able to release node-ffi for v3 because there is an old ref-array dependency

### ISSUE THREAD

**Issue by unbornchikken** [TooTallNate/ref-struct#18]
There: https://github.com/TooTallNate/ref-struct/blob/master/package.json#L31

Please update it to "1", and do a release as soon as possible. Thanks!

**Comment by TooTallNate** [comment]
1.1.2 released.

**Comment by TooTallNate** [comment]
Err, sorry, that was `ref-array`. Struct coming up next.

**Comment by unbornchikken** [comment]
Cool, thanks.

**Comment by TooTallNate** [comment]
Ok, 1.0.2 released now. Lmk if there's any issues!
