### ISSUE TITLE
Struct should not rely on object key order

### ISSUE THREAD

**Issue by kmsquire** [TooTallNate/ref-struct#6]
As noted here: http://stackoverflow.com/questions/9179680/is-it-acceptable-style-for-node-js-libraries-to-rely-on-object-key-order

This is somewhat pedantic, but the code will break if it's ever run on a javascript engine that does not keep track of key order.

**Comment by TooTallNate** [comment]
I don't think either one is _legacy_. I shouldn't have used that word before. They're just alternative syntaxes.

I'll take a pull request showing both styles in the README :wink:
